title: "CyberNeTic"
url: "http://cyberneticproject.eu/"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "ressources"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "technics"
    values:
      layout: "technic"
  - scope:
      path: ""
      type: "study_days"
    values:
      layout: "study_day"

collections:
  pages:
    output: true
    permalink: /:name
  news:
    output: true
    permalink: /actualites/:name
    sort_by: post_date
  ressources:
    output: true
    permalink: /ressources/:name
    sort_by: post_date
  technics:
    output: true
    permalink: /fiches-techniques/:name
    sort_by: title
  study_days:
    output: true
    permalink: /journees-d-etudes/:name
    sort_by: post_date

picture: 
  ignore_missing_images: true