title: "CyberNeTic"
url: "http://cyberneticproject.eu/"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "ressources"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "technics"
    values:
      layout: "technic"

collections:
  pages:
    output: true
    permalink: /:name
  news:
    output: true
    permalink: /actualites/:name
    sort_by: post_date
  ressources:
    output: true
    permalink: /ressources/:name
    sort_by: post_date
  technics:
    output: true
    permalink: /fiches-techniques/:name
    sort_by: post_date