title: "CyberNeTic"
url: "http://cyberneticproject.eu/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "actualites/"
      type: "news"
    values:
      layout: "news"

collections:
  pages:
    output: true
    permalink: /:name
  news:
    layout: news
    output: true
    permalink: /actualites/:name
