title: "CyberNeTic"
url: "http://cyberneticproject.eu/"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  pages:
    output: true
    permalink: /:name