backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: 'assets/uploads'
collections:
  - name: 'post'
    label: 'Posts'
    folder: '_posts/'
    fields:
      - { name: Title }

  - name: 'page'
    label: 'Pages'
    fields:
      - { name: Title }
    files:
      - label: 'Home'
        name: 'home'
        file: '_data/index.yml'
        fields:
          - { label: 'Title', name: 'title', default: 'Home' }
          - { label: 'Body', name: 'body', widget: 'markdown' }


