backend:
  name: git-gateway
  branch: main
local_backend: true

locale: fr

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: ascii
  clean_accents: true


seo: &SEO
  name: seo
  widget: object
  collapsed: true
  fields: 
    - {label: "Title", name: "title", widget: "string", required: false}
    - {label: "Description", name: "description", widget: "text", required: false}
    - {label: "OG Image (shared image)", name: "image", widget: "image", required: false}

image: &IMAGE_FIELDS
  name: image
  label: Featured image
  widget: object
  fields:
    - {name: src, label: Image, widget: image, required: false}
    - {name: alt, label: Alt text, widget: string, required: false}
    - {name: title, label: Title, widget: string, required: false}

markdown_light_button: &MARKDOWN_LIGHT_BUTTONS
  [heading-three, heading-four, heading-five, heading-six, bulleted-list, bold, italic, link]

text_content: &TEXT_CONTENT
  name: text
  label: Contenu
  widget: markdown
  buttons: *MARKDOWN_LIGHT_BUTTONS

collections:
  - name: 'pages'
    label: 'Pages'
    folder: '_pages'
    extension: html
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        required: false
      - *SEO

  - name: 'news'
    label: 'Actualités'
    folder: '_news'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *IMAGE_FIELDS
      - name: preview
        label: Chapô
        required: false
        widget: text
      - name: body
        label: Contenu
        widget: markdown

  - name: 'ressources'
    label: 'Ressources'
    folder: '_ressources'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *IMAGE_FIELDS
      - name: preview
        label: Chapô
        required: false
        widget: text
      - name: body
        label: Contenu
        widget: markdown

  - name: 'technics'
    label: 'Fiche technique'
    folder: '_technics'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - name: subtitle
        label: Sous-titre
        default: "Etiologie des pratiques de cyberharcèlement"
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *IMAGE_FIELDS

      - name: preview
        label: Chapô
        required: false
        widget: text

      - name: synonymous
        label: Synonymes
        required: false
        widget: list

      - name: downloads
        label: Téléchargements
        required: false
        widget: list
        fields: 
          - name: name
            label: string
            required: false
          - name: file
            widget: file
            required: false
            media_library:
              - allow_multiple: false

      - name: definition
        label: Définition
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT


      - name: main
        label: Contenu principal
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *IMAGE_FIELDS

      - name: quote
        label: Citation 
        required: false
        widget: text

      - name: side
        label: Historique 
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *IMAGE_FIELDS

      - name: legals
        label: Cadre légal
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *IMAGE_FIELDS

      - name: ressources
        label: Ressources
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *IMAGE_FIELDS