backend:
  name: git-gateway
  branch: main
local_backend: true

locale: fr

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: ascii
  clean_accents: true

seo: &SEO
  name: seo
  widget: object
  collapsed: true
  fields: 
    - {label: "Title", name: "title", widget: "string", required: false}
    - {label: "Description", name: "description", widget: "text", required: false}
    - {label: "OG Image (shared image)", name: "image", widget: "image", required: false}

image_fields: &IMAGE_FIELDS
  - {name: src, label: Image, widget: image, required: false}
  - {name: alt, label: Alt text, widget: string, required: false}
  - {name: title, label: Title, widget: string, required: false}

featured_image: &FEATURED_IMAGE_FIELDS
  name: image
  label: Featured image
  widget: object
  fields: *IMAGE_FIELDS

markdown_light_button: &MARKDOWN_LIGHT_BUTTONS
  [heading-three, heading-four, heading-five, heading-six, bulleted-list, bold, italic, link]

text_content: &TEXT_CONTENT
  name: text
  label: Contenu
  widget: markdown
  buttons: *MARKDOWN_LIGHT_BUTTONS

page_default_fields: &PAGE_DEFAULT_FIELDS
  - name: title
    label: Title
    required: false
  - *SEO
  - name: introduction
    label: Chapô
    widget: markdown
    buttons: *MARKDOWN_LIGHT_BUTTONS
    required: false

show_warning_field: &WARNING_FIELD
  name: warning
  label: Afficher l'avertissement
  widget: boolean

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: "Accueil"
        name: "home"
        file: "_pages/index.html"
        fields:
        - name: title
          label: Title
          required: false
        - *SEO
        - name: news_title
          label: Titre "actualités"
          required: false
        - name: news_text
          label: Description "actualités"
          required: false
          widget: text
        - name: project_title
          label: Titre "projet"
          required: false
        - name: project_text
          label: Description "projet"
          required: false
          widget: text
        - name: project_img
          label: Image "projet"
          widget: object
          required: false
          fields: *IMAGE_FIELDS
        - name: technics_title
          label: Titre "Fiches techniques"
          required: false
        - name: technics_text
          label: Description "Fiches techniques"
          required: false
          widget: text
        - name: study_days_title
          label: Titre "Journées d'études"
          required: false
        - name: study_days_text
          label: Description "Journées d'études"
          required: false
          widget: text
        - name: ressources_title
          label: Titre "Ressources"
          required: false
        - name: ressources_text
          label: Description "Ressources"
          required: false
          widget: text
        - name: partners_title
          label: Titre "Partenaires"
          required: false
        - name: partners_text
          label: Description "Partenaires"
          required: false
          widget: text
          
      - label: "Projet"
        name: "project"
        file: "_pages/projet.html"
        fields:
          - name: title
            label: Title
            required: false
          - *SEO
          - *TEXT_CONTENT
          - name: team
            label: Équipe
            widget: list
            fields:
              - name: title
                label: Prénom Nom
              - name: job
                label: poste, emploi...
              - *TEXT_CONTENT
              - name: image
                widget: object
                fields: *IMAGE_FIELDS

      - label: "Actualités"
        name: "news"
        file: "_pages/actualites.html"
        fields: *PAGE_DEFAULT_FIELDS

      - label: "Fiches Techniques"
        name: "technics"
        file: "_pages/fiches-techniques.html"
        fields: *PAGE_DEFAULT_FIELDS

      - label: "Journées d'études"
        name: "study_days"
        file: "_pages/journees-d-etudes.html"
        fields: *PAGE_DEFAULT_FIELDS

      - label: "Ressources"
        name: "ressources"
        file: "_pages/ressources.html"
        fields: *PAGE_DEFAULT_FIELDS

  - name: 'news'
    label: 'Actualités'
    folder: '_news'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *FEATURED_IMAGE_FIELDS
      - name: preview
        label: Chapô
        required: false
        widget: text
      - name: body
        label: Contenu
        widget: markdown
      - *WARNING_FIELD

  - name: 'ressources'
    label: 'Ressources'
    folder: '_ressources'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *FEATURED_IMAGE_FIELDS
      - name: preview
        label: Chapô
        required: false
        widget: text
      - name: body
        label: Contenu
        widget: markdown
      - *WARNING_FIELD


  - name: 'study_days'
    label: 'Journées d‘études'
    folder: '_study_days'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - name: subtitle
        label: Sous-titre
        required: false
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *FEATURED_IMAGE_FIELDS
      - name: participants
        label: Participants
        required: false
        widget: array
      - name: downloads
        label: Téléchargements
        required: false
        widget: list
        fields: 
          - name: name
            label: string
            required: false
          - name: file
            widget: file
            required: false
            media_library:
              - allow_multiple: false
      - name: body
        label: Contenu
        widget: markdown
      - *WARNING_FIELD


  - name: 'technics'
    label: 'Fiche technique'
    folder: '_technics'
    extension: html
    create: true
    sortable_fields: 
      - post_date
    editor:
      preview: false
    fields: 
      - name: title
        label: Titre
      - name: subtitle
        label: Sous-titre
        default: "Etiologie des pratiques de cyberharcèlement"
        required: false
      - label: 'Post date'
        name: 'post_date'
        widget: 'date'
      - *SEO
      - *FEATURED_IMAGE_FIELDS

      - name: synonymous
        label: Synonymes
        required: false
        widget: list

      - name: downloads
        label: Téléchargements
        required: false
        widget: list
        fields: 
          - name: name
            label: string
            required: false
          - name: file
            widget: file
            required: false
            media_library:
              - allow_multiple: false

      - name: preview
        label: Chapô
        required: false
        widget: text

      - name: definition
        label: Définition
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT

      - name: main
        label: Contenu principal
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *FEATURED_IMAGE_FIELDS

      - name: quote
        label: Citation 
        required: false
        widget: text

      - name: side
        label: Historique 
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *FEATURED_IMAGE_FIELDS

      - name: legals
        label: Cadre légal
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *FEATURED_IMAGE_FIELDS

      - name: ressources
        label: Ressources
        required: false
        widget: object
        fields:
          - *TEXT_CONTENT
          - *FEATURED_IMAGE_FIELDS
      - *WARNING_FIELD
      

  - name: 'options'
    label: 'Options'
    editor:
      preview: false
    files:
      - file: '_data/options.yml'
        name: 'general'
        label: 'Général'
        fields:
          - name: warning
            label: Message d'avertissement